services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
      - "18888:18888" # Dashboard
      - "4317:18889" # OTLP/gRPC
      - "4318:18890" # OTLP/HTTP
    environment:
      - DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://+:18889
      - DOTNET_DASHBOARD_OTLP_HTTP_ENDPOINT_URL=http://+:18890
