using Dcal;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Dcal.Tests;

public class ApiKeyServiceTests
{
    // 4.3: constant-time API key validation via FixedTimeEquals.
    private static ApiKeyService Build(string key)
    {
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?> { ["DCAL_API_KEY"] = key })
            .Build();
        return new ApiKeyService(config, NullLogger<ApiKeyService>.Instance);
    }

    private static ApiKeyService BuildAutoGenerated(string dataDir, ILogger<ApiKeyService>? logger = null)
    {
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?> { ["DCAL_DATA_DIR"] = dataDir })
            .Build();
        return new ApiKeyService(config, logger ?? NullLogger<ApiKeyService>.Instance);
    }

    private sealed class CapturingLogger : ILogger<ApiKeyService>
    {
        public List<string> Messages { get; } = [];

        public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

        public bool IsEnabled(LogLevel logLevel) => true;

        public void Log<TState>(
            LogLevel logLevel,
            EventId eventId,
            TState state,
            Exception? exception,
            Func<TState, Exception?, string> formatter)
        {
            Messages.Add(formatter(state, exception));
        }
    }

    [Fact]
    public void Validate_CorrectKey_ReturnsTrue()
    {
        var service = Build("super-secret-key");
        Assert.True(service.Validate("super-secret-key"));
    }

    [Fact]
    public void Validate_WrongKeySameLength_ReturnsFalse()
    {
        var service = Build("super-secret-key");
        Assert.False(service.Validate("super-secret-xxx"));
    }

    [Fact]
    public void Validate_WrongKeyDifferentLength_ReturnsFalse()
    {
        var service = Build("super-secret-key");
        Assert.False(service.Validate("short"));
        Assert.False(service.Validate("super-secret-key-with-extra-bytes"));
    }

    [Fact]
    public void Validate_NullOrEmpty_ReturnsFalse()
    {
        var service = Build("super-secret-key");
        Assert.False(service.Validate(null));
        Assert.False(service.Validate(""));
    }

    [Fact]
    public void Validate_NonAsciiKey_RoundTrips()
    {
        var service = Build("clé-secrète-🔑");
        Assert.True(service.Validate("clé-secrète-🔑"));
        Assert.False(service.Validate("clé-secrète-x"));
    }

    [Fact]
    public void AutoGenerate_NoExistingFile_WritesKeyFileAndLogsPathOnly()
    {
        var dataDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var logger = new CapturingLogger();
            var service = BuildAutoGenerated(dataDir, logger);

            var keyPath = Path.Combine(dataDir, "keys", "api-key");
            Assert.True(File.Exists(keyPath));
            Assert.Equal(service.ApiKey, File.ReadAllText(keyPath).Trim());

            Assert.Contains(logger.Messages, m => m.Contains(keyPath));
            Assert.DoesNotContain(logger.Messages, m => m.Contains(service.ApiKey));
        }
        finally
        {
            if (Directory.Exists(dataDir)) Directory.Delete(dataDir, recursive: true);
        }
    }

    [Fact]
    public void AutoGenerate_ExistingFile_ReusesPersistedKeyAcrossRestarts()
    {
        var dataDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var first = BuildAutoGenerated(dataDir);
            var second = BuildAutoGenerated(dataDir);

            Assert.Equal(first.ApiKey, second.ApiKey);
        }
        finally
        {
            if (Directory.Exists(dataDir)) Directory.Delete(dataDir, recursive: true);
        }
    }

    [Fact]
    public void AutoGenerate_NoExistingFile_WritesOwnerOnlyPermissions()
    {
        if (OperatingSystem.IsWindows()) return;

        var dataDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            BuildAutoGenerated(dataDir);

            var keyPath = Path.Combine(dataDir, "keys", "api-key");
            var mode = File.GetUnixFileMode(keyPath);
            Assert.Equal(UnixFileMode.UserRead | UnixFileMode.UserWrite, mode);
        }
        finally
        {
            if (Directory.Exists(dataDir)) Directory.Delete(dataDir, recursive: true);
        }
    }

    [Fact]
    public void AutoGenerate_ExistingFileWithTrailingNewline_TrimsOnRead()
    {
        var dataDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var keysDir = Path.Combine(dataDir, "keys");
            Directory.CreateDirectory(keysDir);
            File.WriteAllText(Path.Combine(keysDir, "api-key"), "somekey\n");

            var service = BuildAutoGenerated(dataDir);

            Assert.Equal("somekey", service.ApiKey);
        }
        finally
        {
            if (Directory.Exists(dataDir)) Directory.Delete(dataDir, recursive: true);
        }
    }
}
