namespace Dmon.Terminal.Tests.Fakes;

public abstract record FakeCall;
public sealed record ScrollbackAppendLine(Dcli.Line Line) : FakeCall;
public sealed record ScrollbackAppendText(string Text) : FakeCall;
public sealed record ScrollbackAppendRule : FakeCall;
public sealed record LiveBegun(int BlockId) : FakeCall;
public sealed record LiveAppendText(int BlockId, string Text) : FakeCall;
public sealed record LiveSetContent(int BlockId, IReadOnlyList<Dcli.Line> Lines) : FakeCall;
public sealed record LiveCommitted(int BlockId) : FakeCall;
public sealed record StatusSet(IReadOnlyList<Dcli.Line> Rows) : FakeCall;
public sealed record SelectOpened(Dcli.SelectRequest Request) : FakeCall;
public sealed record MultiSelectOpened(Dcli.MultiSelectRequest Request) : FakeCall;
public sealed record ChoiceOpened(Dcli.ChoiceRequest Request) : FakeCall;
public sealed record InputOpened(Dcli.InputRequest Request) : FakeCall;
public sealed record InputSetTextCall(string Text) : FakeCall;
public sealed record InputClearCall : FakeCall;
public sealed record InputPreambleSet(IReadOnlyList<Dcli.Line> Rows) : FakeCall;
public sealed record InputSetPromptLine(Dcli.Line Line) : FakeCall;
public sealed record InputSetPromptText(string Text) : FakeCall;
public sealed record Disposed : FakeCall;
